name: fayoumtour
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.1+2

environment:
  sdk: ">=2.17.6 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_svg: ^1.1.0
  equatable:
  get_it:
  flutter_bloc: ^8.0.0
  dio:
  dartz:
  shared_preferences:
  image_picker:
  video_player:
  qr_flutter:
  qr_code_scanner:
  flutter_localizations:
    sdk: flutter
  # light: ^2.1.0
  # flutter_barometer_plugin: ^0.0.1+3
  # flutter_sensors: ^1.0.1
  # cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  atmospeed: ^1.0.2
  youtube_player_flutter:
  lite_rolling_switch:
  flutter_fadein:
  photo_view:
  google_maps_flutter: ^2.2.6
  url_launcher:
  flutter_staggered_grid_view: ^0.6.2
  location: ^4.4.0
  #date_time_picker:
  flutter_credit_card:
  flutter_tts:
  audioplayers:
  animated_splash_screen:
  multi_image_picker:
  intl_utils:
  pull_to_refresh:
  cached_network_image:
  firebase_core:
  firebase_messaging:
  flutter_local_notifications:
  device_preview:
  expandable_text:
  auto_size_text:
  date_format:
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    # - assets/videos/
    - assets/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: KaushanScript
    fonts:
      - asset: assets/fonts/KaushanScript-Regular.ttf
  - family: MyFlutterApp
    fonts:
      - asset: assets/fonts/MyFlutterApp.ttf
  - family: rye
    fonts:
      - asset: assets/fonts/Rye-Regular.ttf
  - family: acme
    fonts:
      - asset: assets/fonts/Acme-Regular.ttf
  - family: aBeeZee
    fonts:
      - asset: assets/fonts/ABeeZee-Regular.ttf
      - asset: assets/fonts/ABeeZee-Italic.ttf
        style: italic
  - family: aclonica
    fonts:
      - asset: assets/fonts/Aclonica-Regular.ttf
  - family: alata
    fonts:
      - asset: assets/fonts/Alata-Regular.ttf
  - family: domine
    fonts:
      - asset: assets/fonts/Domine-VariableFont_wght.ttf
  - family: pressStart2p
    fonts:
      - asset: assets/fonts/PressStart2P-Regular.ttf
  - family: merriweather
    fonts:
      - asset: assets/fonts/Merriweather-Regular.ttf
#-----------------------------------------------------Arabic Fonts--------------------------------------------------------------
  - family: aref
    fonts:
      - asset: assets/fonts/ArefRuqaa-Regular.ttf
  - family: amiri
    fonts:
      - asset: assets/fonts/Amiri-Regular.ttf
  - family: amiriQ
    fonts:
      - asset: assets/fonts/AmiriQuran-Regular.ttf
  - family: messiri
    fonts:
      - asset: assets/fonts/ElMessiri-VariableFont_wght.ttf
  - family: ibmP
    fonts:
      - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
  - family: lemo
    fonts:
      - asset: assets/fonts/Lemonada-VariableFont_wght.ttf
  - family: marhey
    fonts:
      - asset: assets/fonts/Marhey-VariableFont_wght.ttf
  - family: readPro
    fonts:
      - asset: assets/fonts/ReadexPro-VariableFont_HEXP,wght.ttf
  - family: eetsap
    fonts:
      - asset: assets/fonts/alfont_com_eetsap.ttf
  - family: adoody
    fonts:
      - asset: assets/fonts/alfont_com_adoody.ttf
  - family: broken
    fonts:
      - asset: assets/fonts/pt-bold-broken.ttf
  - family: galaxy
    fonts:
      - asset: assets/fonts/AA-GALAXY.ttf
  - family: vlax1
    fonts:
      - asset: assets/fonts/VLAX 01.otf
  - family: vlax2
    fonts:
      - asset: assets/fonts/VLAX 02.otf
  - family: dg
    fonts:
      - asset: assets/fonts/DG-Modal3at-Med.ttf
  - family: Mag
    fonts:
      - asset: assets/fonts/RTL-Maghfira-Ramadan.ttf
  - family: arbT
    fonts:
      - asset: assets/fonts/ArbFONTS-FFKhallab-Regular.ttf
  - family: arbO
    fonts:
      - asset: assets/fonts/ArbFONTS-FFKhallab-Regular.otf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
